# See docs: https://embarkstudios.github.io/cargo-deny/checks/index.html

[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    # `time` crate depends on `stdweb` crate. We need to wait for
    # when `time` crate will be updated
    #
    # Original error message:
    # The author of the `stdweb` crate is unresponsive.
    "RUSTSEC-2020-0056"
]

[bans]
multiple-versions = "deny"
skip = [
    # We depend on older version of this crate through deps: `structopt -> clap`
    { version = "0.11.0", name = "ansi_term" }
    # { version = "0.42.1", name = "crate_name_here" },
]
skip-tree = [
    # { version = "0.42.0", name = "crate_name_here", depth = 6 },
]
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[licenses]
unlicensed = "deny"
copyleft = "deny"

# Run `cargo deny list` to see which crates use which license
# and add them to this array if you accept them
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "OpenSSL",
]
deny = []
default = "deny"
allow-osi-fsf-free = "neither"

# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93

[[licenses.clarify]]
# This crate has a low-confidence license inference score (0.85), so clarifying manually...
# This license here is complicated (https://github.com/briansmith/webpki/pull/128)
# So let's just put `ISC` here for now...
name = "webpki"
version = "0.21.3"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c }
]
[[licenses.clarify]]
name = "ring"
version = "0.16.15"
# Copied this expression from the comment of Jake-Shadle (maintainer of cargo-deny)
# https://github.com/EmbarkStudios/cargo-deny/issues/110#issuecomment-576173641
# The issue under ring repo:
# https://github.com/briansmith/ring/issues/902
expression = "ISC AND MIT AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]
